# Change again..
name: Java CI with Gradle

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Run gradle-build-action
      uses: gradle/gradle-build-action@v2
      with:
        build-root-directory: groovy-dsl-project
        arguments: help --build-cache
    
        
